Config = {}
-- Config for the menu
Config.MenuTitle = 'Youtool'
Config.MenuDescription = 'Preview & Achat de Props'

Config.MenuLocation = 'topright'
Config.MenutColorR = 255
Config.MenutColorG = 0
Config.MenutColorB = 0
Config.MenuSize = 'size-125'
Config.MenuFont = 'default'

Config.MenuNamespace = 'prop_visualizer'
Config.MenuNamespace2 = 'prop_visualizer2'

Config.MenuItemIcon = '🗿'
Config.MenuItemDescription = 'Appuyez sur ENTRER pour acheter '
Config.MenuItemDescription2 = 'Appuyez sur ENTRER pour découvrir la catégorie '

-- Config shops locations
Config.Shops = {
    [1] = {
        coords = vector4(2761.31, 3495.36, 54.39, 252.56),
        shopItemName = 'YOUTOOL',
        model = `a_m_m_business_01`,
        targetLabel = 'Achetez des Props',
        targetIcon = 'fas fa-shop',
        targetDistance = 2.0,
        previewCoords = vector3(2770.48, 3497.06, 55.24),
    },
    -- Add more shops as needed
}

-- Config for the props list (only used for /proplist_menu command)
Config.Props = {
    {label = 'Box de carton',               model = 'prop_boxpile_07d',                 price = 100},
    {label = 'Cone de circulation',         model = 'prop_roadcone02a',                 price = 200},
    {label = 'Barrière',                    model = 'prop_barrier_work05',              price = 300},
    {label = 'Chaise',                      model = 'prop_chair_01a',                   price = 400},
    {label = 'Table',                       model = 'prop_table_03',                    price = 500},
    {label = 'Canapé',                      model = 'prop_couch_01',                    price = 800},
    {label = 'Lit',                         model = 'prop_bed_01',                      price = 1000},
    {label = 'Bureau',                      model = 'prop_desk_01',                     price = 750},
    {label = 'Armoire',                     model = 'prop_cabinet_01',                  price = 600},
    {label = 'Télévision',                  model = 'prop_tv_flat_01',                  price = 1200},
    {label = 'Lampe',                       model = 'prop_lamp_01',                     price = 300},
    {label = 'Plante',                      model = 'prop_plant_int_01a',              price = 250},
    {label = 'Tapis',                       model = 'prop_rug_01',                      price = 400},
    {label = 'Bibliothèque',               model = 'prop_bookshelf_01',                price = 900},
    {label = 'Micro-ondes',                model = 'prop_microwave_1',                 price = 450},
    {label = 'Réfrigérateur',              model = 'prop_fridge_01',                   price = 1500},
    {label = 'Machine à laver',            model = 'prop_washing_machine_1',           price = 1300},
    {label = 'Poubelle',                   model = 'prop_bin_01a',                     price = 150},
    {label = 'Ventilateur',                model = 'prop_fan_01',                      price = 200},
    {label = 'Radio',                      model = 'prop_radio_01',                    price = 350},
    {label = 'Ordinateur',                 model = 'prop_pc_01a',                      price = 1000},
    {label = 'Imprimante',                 model = 'prop_printer_01',                  price = 400},
    {label = 'Tableau',                    model = 'prop_painting_01',                 price = 600},
    {label = 'Horloge murale',            model = 'prop_clock_01',                    price = 250},
    {label = 'Miroir',                     model = 'prop_mirror_01',                   price = 300},
    {label = 'Guitare',                    model = 'prop_guitar_01',                   price = 800},
    {label = 'Piano',                      model = 'prop_piano_01',                    price = 2000},
    {label = 'Batterie',                   model = 'prop_drum_kit_01',                 price = 1500},
    {label = 'Barbecue',                   model = 'prop_bbq_1',                       price = 700},
    {label = 'Parasol',                    model = 'prop_parasol_01',                  price = 400},
    {label = 'Chaise de jardin',          model = 'prop_chair_02',                    price = 300},
    {label = 'Table de jardin',           model = 'prop_table_02',                    price = 450},
    {label = 'Hamac',                      model = 'prop_hammock_01',                  price = 500},
    {label = 'Balançoire',                model = 'prop_swing_01',                    price = 600},
    {label = 'Toboggan',                   model = 'prop_slide_01',                    price = 800},
    {label = 'Piscine gonflable',         model = 'prop_pool_01',                     price = 1000},
    {label = 'Vélo',                       model = 'prop_bike_01',                     price = 500},
    {label = 'Skateboard',                 model = 'prop_skateboard_01',               price = 300},
    {label = 'Ballon de foot',            model = 'prop_football_01',                 price = 100},
    {label = 'Ballon de basket',          model = 'prop_basketball_01',               price = 100},
    {label = 'Raquette de tennis',        model = 'prop_tennis_rack_01',              price = 200},
    {label = 'Club de golf',              model = 'prop_golf_club_01',                price = 400},
    {label = 'Sac de boxe',               model = 'prop_boxing_bag_01',               price = 500},
    {label = 'Haltères',                   model = 'prop_weight_1',                    price = 300},
    {label = 'Tapis de yoga',             model = 'prop_yoga_mat_01',                 price = 150},
    {label = 'Banc de musculation',       model = 'prop_weight_bench_01',             price = 800},
    {label = 'Échelle',                    model = 'prop_ladder_01',                   price = 400},
    {label = 'Boîte à outils',            model = 'prop_toolbox_01',                  price = 300},
    {label = 'Marteau',                    model = 'prop_hammer_01',                   price = 100},
    {label = 'Scie',                       model = 'prop_saw_01',                      price = 150},
    {label = 'Perceuse',                   model = 'prop_drill_01',                    price = 200},
    {label = 'Pelle',                      model = 'prop_shovel_01',                   price = 150},
    {label = 'Râteau',                     model = 'prop_rake_01',                     price = 120},
    {label = 'Tondeuse',                   model = 'prop_lawnmower_01',               price = 600},
    {label = 'Arrosoir',                   model = 'prop_wateringcan',                 price = 100},
    {label = 'Pot de fleurs',             model = 'prop_flowerpot_01',               price = 150},
    {label = 'Statue de jardin',          model = 'prop_garden_statue',              price = 800},
    {label = 'Fontaine',                   model = 'prop_fountain_01',                 price = 1200},
    {label = 'Lanterne',                   model = 'prop_lantern_01',                  price = 250},
    {label = 'Panneau solaire',           model = 'prop_solar_panel',                price = 2000},
    {label = 'Éolienne',                   model = 'prop_windmill_01',                 price = 2500},
    {label = 'Composteur',                model = 'prop_composter',                   price = 400},
    {label = 'Récupérateur d\'eau',       model = 'prop_water_collector',            price = 600},
    {label = 'Serre',                      model = 'prop_greenhouse_01',               price = 1500},
    {label = 'Poulailler',                model = 'prop_chicken_coop',                price = 1000},
    {label = 'Niche',                      model = 'prop_doghouse_01',                 price = 500},
    {label = 'Aquarium',                   model = 'prop_aquarium_01',                price = 800},
    {label = 'Cage à oiseaux',            model = 'prop_birdcage_01',                price = 400},
    {label = 'Terrarium',                  model = 'prop_terrarium_01',               price = 600},
    {label = 'Ruche',                      model = 'prop_beehive_01',                 price = 1000},
    {label = 'Épouvantail',               model = 'prop_scarecrow_01',               price = 300},
    {label = 'Brouette',                   model = 'prop_wheelbarrow_01',             price = 350},
    {label = 'Commode',                    model = 'prop_dresser_01',                 price = 700},
    {label = 'Table de chevet',           model = 'prop_bedside_table_01',           price = 400},
    {label = 'Porte-manteau',             model = 'prop_coatstand_01',               price = 250},
    {label = 'Panier à linge',            model = 'prop_laundry_basket_01',          price = 150},
    {label = 'Séchoir à linge',           model = 'prop_clothesline_01',             price = 200},
    {label = 'Fer à repasser',            model = 'prop_iron_01',                    price = 150},
    {label = 'Planche à repasser',        model = 'prop_ironing_board_01',           price = 200},
    {label = 'Aspirateur',                model = 'prop_vacuum_01',                   price = 400},
    {label = 'Balai',                      model = 'prop_broom_01',                   price = 100},
    {label = 'Serpillière',               model = 'prop_mop_01',                     price = 100},
    {label = 'Seau',                       model = 'prop_bucket_01',                  price = 80},
    {label = 'Éponge',                     model = 'prop_sponge_01',                  price = 50},
    {label = 'Produit ménager',           model = 'prop_cleaning_spray',             price = 100},
    {label = 'Désodorisant',              model = 'prop_air_freshener',              price = 80},
    {label = 'Papier toilette',           model = 'prop_toilet_paper_01',            price = 50},
    {label = 'Savon',                      model = 'prop_soap_01',                    price = 30},
    {label = 'Serviette',                  model = 'prop_towel_01',                   price = 100},
    {label = 'Tapis de bain',             model = 'prop_bath_mat_01',                price = 150},
    {label = 'Rideau de douche',          model = 'prop_shower_curtain',             price = 200},
    {label = 'Porte-savon',               model = 'prop_soap_holder',                price = 100},
    {label = 'Brosse à dents',            model = 'prop_toothbrush_01',              price = 50},
    {label = 'Dentifrice',                model = 'prop_toothpaste_01',              price = 30},
    {label = 'Peigne',                     model = 'prop_comb_01',                    price = 40},
    {label = 'Brosse à cheveux',          model = 'prop_hairbrush_01',               price = 60},
    {label = 'Sèche-cheveux',             model = 'prop_hairdryer_01',               price = 200},
    {label = 'Rasoir',                     model = 'prop_razor_01',                   price = 80},
    {label = 'Crème à raser',             model = 'prop_shaving_cream',              price = 60},
    {label = 'Coton-tige',                model = 'prop_cotton_swab',                price = 30},
    {label = 'Pansement',                  model = 'prop_bandage_01',                 price = 40},
    {label = 'Trousse de premiers soins', model = 'prop_first_aid_kit',             price = 300},
    {label = 'Thermomètre',               model = 'prop_thermometer_01',             price = 100},
    {label = 'Balance',                    model = 'prop_scale_01',                   price = 150},
    {label = 'Pèse-personne',             model = 'prop_weighing_scale',             price = 200},
    {label = 'Miroir grossissant',        model = 'prop_magnifying_mirror',          price = 250},
    {label = 'Tabouret de salle de bain', model = 'prop_bathroom_stool',            price = 150},
    {label = 'Porte-serviettes',          model = 'prop_towel_rail_01',             price = 120},
    {label = 'Porte-papier toilette',     model = 'prop_toilet_roll_holder',        price = 80},
    {label = 'Poubelle de salle de bain', model = 'prop_bathroom_bin',              price = 100},
    {label = 'Tapis antidérapant',        model = 'prop_nonslip_mat',               price = 120},
    {label = 'Distributeur de savon',     model = 'prop_soap_dispenser',            price = 150},
    {label = 'Porte-brosses à dents',     model = 'prop_toothbrush_holder',         price = 100},
    {label = 'Panier à linge sale',       model = 'prop_laundry_basket_02',         price = 180},
    {label = 'Séchoir mural',             model = 'prop_wall_dryer',                price = 250},
    {label = 'Patère murale',             model = 'prop_wall_hook',                 price = 80}
    -- Add more props as needed
}

Config.ShopItemList = {
    ['YOUTOOL'] = {
        ["LSPD"] = {
            {label = 'Box de carton',               model = 'prop_boxpile_07d',                 price = 100},
            {label = 'Cone de circulation',         model = 'prop_roadcone02a',                 price = 200},
            {label = 'Barrière',                    model = 'prop_barrier_work05',              price = 300},
            {label = 'Barrière 2',                  model = 'prop_barrier_work06a',             price = 300},
            {label = 'Barrière 3',                  model = 'prop_mp_barrier_02b',              price = 300},
            {label = 'Barrière 4',                  model = 'prop_mp_arrow_barrier_01',          price = 300},
        },
        ["Tables"] = {
            {label = 'Table',                       model = 'prop_table_03',                    price = 500},
            {label = 'Table de salon',              model = 'apa_mp_h_din_table_01',            price = 400},
            {label = 'Table de salon 2',            model = 'apa_mp_h_din_table_04',            price = 400},
            {label = 'Table de salon 3',            model = 'apa_mp_h_din_table_06',            price = 400},
            {label = 'Table de salon 4',            model = 'apa_mp_h_yacht_coffee_table_01',   price = 400},
            {label = 'Table de salon 5',            model = 'apa_mp_h_yacht_coffee_table_02',   price = 400},
            {label = 'Table de salon 6',            model = 'apa_mp_h_yacht_side_table_01',     price = 400},
            {label = 'Table de salon 7',            model = 'apa_mp_h_yacht_side_table_02',     price = 400},
            {label = 'Table de salon 8',            model = 'apa_mp_h_din_table_05',            price = 400},
            {label = 'Table de salon 9',            model = 'apa_mp_h_din_table_06',            price = 400},
            {label = 'Table de salon 10',           model = 'ex_prop_ex_console_table_01',      price = 400},
            {label = 'Table de salon 11',           model = 'gr_dlc_gr_yacht_props_table_02',   price = 400},
            {label = 'Table de salon 12',           model = 'hei_heist_din_table_07',           price = 400},
            {label = 'Table de salon 13',           model = 'prop_chateau_table_01',            price = 400},
            {label = 'Table de salon 14',           model = 'prop_picnictable_01_lod',          price = 400},
            {label = 'Table de salon 15',           model = 'prop_proxy_chateau_table',         price = 400},
            {label = 'Table de salon 16',           model = 'prop_table_02',                    price = 400},
            {label = 'Table de salon 17',           model = 'prop_table_04',                    price = 400},
            {label = 'Table de salon 18',           model = 'prop_table_05',                    price = 400},
            {label = 'Table de salon 19',           model = 'lav_ret_fh_dinetable',             price = 400},
        },
        ["Chaises"] = {
            {label = 'Chaise',                      model = 'apa_mp_h_din_chair_08',            price = 400},
            {label = 'Chaise 2',                    model = 'apa_mp_h_din_chair_12',            price = 400},
            {label = 'Chaise 3',                    model = 'apa_mp_h_stn_chairarm_02',         price = 400},
            {label = 'Chaise 4',                    model = 'apa_mp_h_stn_chairarm_09',         price = 400},
            {label = 'Chaise 5',                    model = 'apa_mp_h_stn_chairarm_11',         price = 400},
            {label = 'Chaise 6',                    model = 'apa_mp_h_stn_chairarm_12',         price = 400},
            {label = 'Chaise 7',                    model = 'apa_mp_h_stn_chairarm_13',         price = 400},
            {label = 'Tabouret',                    model = 'apa_mp_h_stn_chairstool_12',       price = 300},
            {label = 'Chaise de bureau',            model = 'bkr_prop_biker_boardchair01',      price = 450},
            {label = 'Chaise de club',              model = 'bkr_prop_clubhouse_chair_01',      price = 400},
            {label = 'Chaise de bureau exec 1',     model = 'ex_prop_offchair_exec_01',         price = 600},
            {label = 'Chaise de bureau exec 2',     model = 'ex_prop_offchair_exec_03',         price = 600},
            {label = 'Chaise 8',                    model = 'gr_prop_gr_chair02_ped',           price = 400},
            {label = 'Chaise haut de gamme',        model = 'gr_prop_highendchair_gr_01a',      price = 800},
            {label = 'Chaise de salle à manger 1',  model = 'hei_heist_din_chair_01',          price = 450},
            {label = 'Chaise de salle à manger 2',  model = 'hei_heist_din_chair_06',          price = 450},
            {label = 'Chaise simple',               model = 'hei_prop_hei_skid_chair',          price = 200},
            {label = 'Chaise de bureau 3',          model = 'hei_prop_heist_off_chair',         price = 500},
            {label = 'Chaise de salle à manger 3',  model = 'p_dinechair_01_s',                price = 450},
            {label = 'Chaise pliante',              model = 'p_folding_chair_01_s',             price = 250},
            {label = 'Chaise simple 2',             model = 'prop_chair_01a',                   price = 300},
            {label = 'Chaise simple 3',             model = 'prop_chair_01b',                   price = 300},
            {label = 'Chaise simple 4',             model = 'prop_chair_02',                    price = 300},
            {label = 'Chaise simple 5',             model = 'prop_chair_03',                    price = 300},
            {label = 'Chaise simple 6',             model = 'prop_chair_07',                    price = 300},
            {label = 'Chaise simple 7',             model = 'prop_chair_08',                    price = 300},
            {label = 'Pile de chaises',             model = 'prop_chair_pile_01',               price = 1000},
            {label = 'Chaise simple 8',             model = 'prop_chair_09',                    price = 300},
            {label = 'Chaise château',              model = 'prop_chateau_chair_01',            price = 600},
            {label = 'Chaise de réalisateur',       model = 'prop_direct_chair_01',             price = 500},
            {label = 'Chaise pliante 2',            model = 'prop_flipchair_01',                price = 250},
            {label = 'Chaise de bureau 4',          model = 'prop_off_chair_03',                price = 500},
            {label = 'Chaise de bureau 5',          model = 'prop_off_chair_05',                price = 500},
            {label = 'Chaise longue 1',             model = 'prop_old_deck_chair',              price = 400},
            {label = 'Chaise longue 2',             model = 'prop_old_deck_chair_02',           price = 400},
            {label = 'Chaise en bois',              model = 'prop_old_wood_chair',              price = 350},
            {label = 'Chaise berçante',             model = 'prop_rock_chair_01',               price = 450},
            {label = 'Chaise simple 9',             model = 'prop_skid_chair_01',               price = 300},
            {label = 'Chaise simple 10',            model = 'prop_skid_chair_02',               price = 300},
            {label = 'Chaise simple 11',            model = 'prop_skid_chair_03',               price = 300},
            {label = 'Chaise de bureau 6',          model = 'v_corp_cd_chair',                  price = 500},
            {label = 'Chaise salon',                model = 'v_res_m_l_chair1',                 price = 400},
            {label = 'Chaise maison',               model = 'v_ret_fh_chair01',                 price = 350},
            {label = 'Chaise sous-marin',           model = 'xm_int_lev_sub_chair_01',          price = 450},
        },
        ["Canapés"] = {
            {label = 'Canapé',                      model = 'prop_couch_01',                    price = 800},
            {label = 'Canapé 2',                    model = 'prop_couch_03',                    price = 800},
            {label = 'Canapé 3',                    model = 'prop_couch_04',                    price = 800},
            {label = 'Grand canapé 1',              model = 'prop_couch_lg_02',                 price = 1000},
            {label = 'Grand canapé 2',              model = 'prop_couch_lg_05',                 price = 1000},
            {label = 'Grand canapé 3',              model = 'prop_couch_lg_06',                 price = 1000},
            {label = 'Grand canapé 4',              model = 'prop_couch_lg_07',                 price = 1000},
            {label = 'Grand canapé 5',              model = 'prop_couch_lg_08',                 price = 1000},
            {label = 'Petit canapé 1',              model = 'prop_couch_sm1_07',                price = 600},
            {label = 'Petit canapé 2',              model = 'prop_couch_sm2_07',                price = 600},
            {label = 'Petit canapé 3',              model = 'prop_couch_sm_05',                 price = 600},
            {label = 'Petit canapé 4',              model = 'prop_couch_sm_06',                 price = 600},
            {label = 'Petit canapé 5',              model = 'prop_couch_sm_07',                 price = 600},
            {label = 'Canapé ferme',                model = 'prop_ld_farm_couch01',             price = 700},
            {label = 'Vieux canapé 1',              model = 'prop_rub_couch03',                 price = 400},
            {label = 'Vieux canapé 2',              model = 'prop_rub_couch04',                 price = 400},
            {label = 'Canapé 2 places 1',           model = 'hei_heist_stn_sofa2seat_03',       price = 800},
            {label = 'Canapé 2 places 2',           model = 'hei_heist_stn_sofa2seat_06',       price = 800},
            {label = 'Canapé 3 places 1',           model = 'hei_heist_stn_sofa3seat_01',       price = 1000},
            {label = 'Canapé 3 places 2',           model = 'hei_heist_stn_sofa3seat_02',       price = 1000},
            {label = 'Canapé 3 places 3',           model = 'hei_heist_stn_sofa3seat_06',       price = 1000},
        },
        ["Fauteuils"] = {
            {label = 'Fauteuil de laboratoire',     model = 'xm_lab_chairarm_25',              price = 500},
            {label = 'Fauteuil de ferme',           model = 'prop_ld_farm_chair01',            price = 400},
            {label = 'Fauteuil simple',             model = 'prop_sol_chair',                  price = 450},
            {label = 'Fauteuil de yacht',           model = 'prop_yaught_chair_01',            price = 600},
            {label = 'Fauteuil élégant 1',          model = 'hei_heist_stn_chairarm_01',       price = 550},
            {label = 'Fauteuil club 1',             model = 'hei_heist_stn_chairstrip_01',     price = 500},
            {label = 'Fauteuil élégant 2',          model = 'hei_heist_stn_chairarm_03',       price = 550},
            {label = 'Fauteuil élégant 3',          model = 'hei_heist_stn_chairarm_04',       price = 550},
            {label = 'Fauteuil élégant 4',          model = 'hei_heist_stn_chairarm_06',       price = 550},
            {label = 'Fauteuil classique',          model = 'p_armchair_01_s',                 price = 500},
            {label = 'Fauteuil de bureau',          model = 'p_soloffchair_s',                 price = 450},
            {label = 'Fauteuil de yacht 2',         model = 'p_yacht_chair_01_s',              price = 600},
            {label = 'Fauteuil simple 2',           model = 'prop_armchair_01',                price = 450},
            {label = 'Fauteuil de club',            model = 'bkr_prop_clubhouse_armchair_01a', price = 500},
            {label = 'Fauteuil de bureau 2',        model = 'ex_mp_h_off_chairstrip_01',       price = 450},
            {label = 'Fauteuil club 2',             model = 'ex_mp_h_stn_chairstrip_01',       price = 500},
            {label = 'Fauteuil club 3',             model = 'ex_mp_h_stn_chairstrip_010',      price = 500},
            {label = 'Fauteuil club 4',             model = 'ex_mp_h_stn_chairstrip_011',      price = 500},
            {label = 'Fauteuil club 5',             model = 'ex_mp_h_stn_chairstrip_05',       price = 500},
            {label = 'Fauteuil club 6',             model = 'ex_mp_h_stn_chairstrip_07',       price = 500},
            {label = 'Fauteuil moderne 1',          model = 'apa_mp_h_stn_chairarm_01',        price = 600},
            {label = 'Fauteuil moderne 2',          model = 'apa_mp_h_stn_chairarm_23',        price = 600},
            {label = 'Fauteuil moderne 3',          model = 'apa_mp_h_stn_chairarm_25',        price = 600},
            {label = 'Fauteuil moderne 4',          model = 'apa_mp_h_stn_chairarm_26',        price = 600},
            {label = 'Fauteuil club moderne 1',     model = 'apa_mp_h_stn_chairstrip_01',      price = 550},
            {label = 'Fauteuil club moderne 2',     model = 'apa_mp_h_stn_chairstrip_02',      price = 550},
            {label = 'Fauteuil club moderne 3',     model = 'apa_mp_h_stn_chairstrip_03',      price = 550},
            {label = 'Fauteuil club moderne 4',     model = 'apa_mp_h_stn_chairstrip_04',      price = 550},
            {label = 'Fauteuil club moderne 5',     model = 'apa_mp_h_stn_chairstrip_05',      price = 550},
            {label = 'Fauteuil club moderne 6',     model = 'apa_mp_h_stn_chairstrip_06',      price = 550},
            {label = 'Fauteuil club moderne 7',     model = 'apa_mp_h_stn_chairstrip_07',      price = 550},
            {label = 'Fauteuil club moderne 8',     model = 'apa_mp_h_stn_chairstrip_08',      price = 550},
            {label = 'Fauteuil de yacht luxe 1',    model = 'apa_mp_h_yacht_armchair_01',      price = 700},
            {label = 'Fauteuil de yacht luxe 2',    model = 'apa_mp_h_yacht_armchair_04',      price = 700},
            {label = 'Fauteuil de motard 1',        model = 'bkr_prop_biker_chairstrip_01',    price = 450},
            {label = 'Fauteuil de motard 2',        model = 'bkr_prop_biker_chairstrip_02',    price = 450},
        },
        ["Lits"] = {
            {label = 'Lit double moderne 1',        model = 'apa_mp_h_bed_double_08',          price = 1200},
            {label = 'Lit double moderne 2',        model = 'apa_mp_h_bed_double_09',          price = 1200},
            {label = 'Grand lit moderne',           model = 'apa_mp_h_bed_wide_05',            price = 1500},
            {label = 'Lit avec table de chevet',    model = 'apa_mp_h_bed_with_table_02',      price = 1300},
            {label = 'Lit de yacht 1',              model = 'apa_mp_h_yacht_bed_01',           price = 2000},
            {label = 'Lit de yacht 2',              model = 'apa_mp_h_yacht_bed_02',           price = 2000},
            {label = 'Lit de camp',                 model = 'bkr_prop_biker_campbed_01',       price = 500},
            {label = 'Lit exécutif',               model = 'ex_prop_exec_bed_01',             price = 1800},
            {label = 'Lit de bunker',              model = 'gr_prop_bunker_bed_01',           price = 800},
            {label = 'Lit double luxe',            model = 'hei_heist_bed_double_08',         price = 1500},
            {label = 'Lit de Lester',              model = 'p_lestersbed_s',                  price = 1000},
            {label = 'Lit moderne',                model = 'p_mbbed_s',                       price = 1200},
            {label = 'Lit résidentiel',            model = 'p_v_res_tt_bed_s',               price = 1100},
            {label = 'Lit de maison',              model = 'v_res_msonbed_s',                price = 1000},
        },
        ["Bureaux"] = {
            {label = 'Bureau de bureau',            model = 'prop_office_desk_01',             price = 750},
            {label = 'Bureau du personnel 1',       model = 'xm_prop_base_staff_desk_01',      price = 800},
            {label = 'Bureau du personnel 2',       model = 'xm_prop_base_staff_desk_02',      price = 800},
        },
        ["Armoires"] = {
            {label = 'Armoire',                     model = 'prop_cabinet_01',                  price = 600},
            {label = 'Armoire 2',                    model = 'prop_cabinet_01b',                 price = 600},
            {label = 'Armoire 3',                    model = 'prop_cabinet_02b',                 price = 600},
            {label = 'Armoire rustique',             model = 'prop_rub_cabinet',                 price = 500},
            {label = 'Meuble TV 1',                  model = 'prop_tv_cabinet_03',               price = 800},
            {label = 'Meuble TV 2',                  model = 'prop_tv_cabinet_04',               price = 800},
            {label = 'Meuble TV 3',                  model = 'prop_tv_cabinet_05',               price = 800},
            {label = 'Porte d\'armoire',             model = 'xm_prop_base_cabinet_door_01',     price = 300},
        },
        ["Télévisions"] = {
            {label = 'Télévision',                  model = 'prop_tv_flat_01',                  price = 1200},
            {label = 'Télévision plate 2',          model = 'prop_tv_flat_02',                  price = 1200},
            {label = 'Télévision plate 2B',         model = 'prop_tv_flat_02b',                 price = 1200},
            {label = 'Télévision plate 3',          model = 'prop_tv_flat_03',                  price = 1200},
            {label = 'Télévision plate 3B',         model = 'prop_tv_flat_03b',                 price = 1200},
            {label = 'Télévision 3',                model = 'prop_tv_03',                       price = 1000},
            {label = 'Télévision 4',                model = 'prop_tv_04',                       price = 1000},
            {label = 'Télévision de Michael',       model = 'prop_tv_flat_michael',             price = 1500},
        },
        ["Lampes"] = {
            {label = 'Lampadaire moderne',          model = 'apa_mp_h_floor_lamp_int_08',      price = 400},
            {label = 'Lampadaire A',                model = 'apa_mp_h_floorlamp_a',            price = 350},
            {label = 'Lampadaire B',                model = 'apa_mp_h_floorlamp_b',            price = 350}, 
            {label = 'Lampadaire C',                model = 'apa_mp_h_floorlamp_c',            price = 350},
            {label = 'Lampadaire design 1',         model = 'apa_mp_h_lit_floorlamp_01',       price = 450},
            {label = 'Lampadaire design 5',         model = 'apa_mp_h_lit_floorlamp_05',       price = 450},
            {label = 'Lampadaire design 6',         model = 'apa_mp_h_lit_floorlamp_06',       price = 450},
            {label = 'Lampadaire design 10',        model = 'apa_mp_h_lit_floorlamp_10',       price = 450},
            {label = 'Lampadaire design 13',        model = 'apa_mp_h_lit_floorlamp_13',       price = 450},
            {label = 'Lampadaire design 17',        model = 'apa_mp_h_lit_floorlamp_17',       price = 450},
            {label = 'Lampe de nuit 7',             model = 'apa_mp_h_lit_floorlampnight_07',   price = 300},
            {label = 'Lampe de nuit 14',            model = 'apa_mp_h_lit_floorlampnight_14',   price = 300},
            {label = 'Lampe de table 005',          model = 'apa_mp_h_lit_lamptable_005',      price = 250},
            {label = 'Lampe de table 09',           model = 'apa_mp_h_lit_lamptable_09',       price = 250},
            {label = 'Lampe de table 14',           model = 'apa_mp_h_lit_lamptable_14',       price = 250},
            {label = 'Lampadaire de yacht',         model = 'apa_mp_h_yacht_floor_lamp_01',    price = 500},
            {label = 'Lampe trépied A',             model = 'xm_prop_base_tripod_lampa',       price = 400},
            {label = 'Lampe trépied B',             model = 'xm_prop_base_tripod_lampb',       price = 400},
            {label = 'Lampe trépied C',             model = 'xm_prop_base_tripod_lampc',       price = 400},
            {label = 'Lampe de laboratoire B',      model = 'xm_prop_lab_tube_lampb',          price = 350},
            -- Bzzz - Lampe trépied
            {label = 'Lampe trépied - Bleu',      model = 'bzzz_dream_of_lights_blue',          price = 350},
            {label = 'Lampe trépied - Verte',      model = 'bzzz_dream_of_lights_green',          price = 350},
            {label = 'Lampe trépied - Orange',      model = 'bzzz_dream_of_lights_orange',          price = 350},
            {label = 'Lampe trépied - Rose',      model = 'bzzz_dream_of_lights_pink',          price = 350},
            {label = 'Lampe trépied - Violet',      model = 'bzzz_dream_of_lights_purple',          price = 350},
            {label = 'Lampe trépied - Rouge',      model = 'bzzz_dream_of_lights_red',          price = 350},
            {label = 'Lampe trépied - Blanc',      model = 'bzzz_dream_of_lights_white',          price = 350},
            {label = 'Lampe trépied - Jaune',      model = 'bzzz_dream_of_lights_yellow',          price = 350},
            -- Bzzz - Lampe trépied au sol
            {label = 'Lampe trépied au sol - Bleu',      model = 'bzzz_world_of_lamps_blue',          price = 350},
            {label = 'Lampe trépied au sol - Verte',      model = 'bzzz_world_of_lamps_green',          price = 350},
            {label = 'Lampe trépied au sol - Orange',      model = 'bzzz_world_of_lamps_orange',          price = 350},
            {label = 'Lampe trépied au sol - Rose',      model = 'bzzz_world_of_lamps_pink',          price = 350},
            {label = 'Lampe trépied au sol - Violet',      model = 'bzzz_world_of_lamps_purple',          price = 350},
            {label = 'Lampe trépied au sol - Rouge',      model = 'bzzz_world_of_lamps_red',          price = 350},
            {label = 'Lampe trépied au sol - Blanc',      model = 'bzzz_world_of_lamps_white',          price = 350},
            {label = 'Lampe trépied au sol - Jaune',      model = 'bzzz_world_of_lamps_yellow',          price = 350},
            

        },
        ["Plantes"] = {
            {label = 'Plante',                      model = 'prop_plant_int_01a',              price = 250},
            {label = 'Palmier d\'intérieur',          model = 'apa_mp_h_acc_plant_palm_01',       price = 400},
            {label = 'Grande plante',                 model = 'apa_mp_h_acc_plant_tall_01',       price = 450},
            {label = 'Plante bijouterie 1',           model = 'p_int_jewel_plant_01',             price = 300},
            {label = 'Plante bijouterie 2',           model = 'p_int_jewel_plant_02',             price = 300},
            {label = 'Plante FBI',                    model = 'prop_fbibombplant',                price = 350},
            {label = 'Plante d\'intérieur 1A',        model = 'prop_plant_int_01a',              price = 250},
            {label = 'Plante d\'intérieur 1B',        model = 'prop_plant_int_01b',              price = 250},
            {label = 'Plante d\'intérieur 2A',        model = 'prop_plant_int_02a',              price = 250},
            {label = 'Plante d\'intérieur 2B',        model = 'prop_plant_int_02b',              price = 250},
            {label = 'Plante d\'intérieur 4A',        model = 'prop_plant_int_04a',              price = 250},
            {label = 'Plante d\'intérieur 4B',        model = 'prop_plant_int_04b',              price = 250},
            {label = 'Plante d\'intérieur 4C',        model = 'prop_plant_int_04c',              price = 250},
            {label = 'Plante en pot 1A',              model = 'prop_pot_plant_01a',              price = 200},
            {label = 'Plante en pot 1B',              model = 'prop_pot_plant_01b',              price = 200},
            {label = 'Plante en pot 1C',              model = 'prop_pot_plant_01c',              price = 200},
            {label = 'Plante en pot 1D',              model = 'prop_pot_plant_01d',              price = 200},
            {label = 'Plante en pot 1E',              model = 'prop_pot_plant_01e',              price = 200},
            {label = 'Plante en pot 3A',              model = 'prop_pot_plant_03a',              price = 200},
            {label = 'Plante en pot 6A',              model = 'prop_pot_plant_6a',               price = 200},
            {label = 'Plante en pot 6B',              model = 'prop_pot_plant_6b',               price = 200},
        },
        ["Tapis"] = {
            {label = 'Tapis en laine M1',            model = 'apa_mp_h_acc_rugwoolm_01',         price = 400},
            {label = 'Tapis en laine M2',            model = 'apa_mp_h_acc_rugwoolm_02',         price = 400},
            {label = 'Tapis en laine M3',            model = 'apa_mp_h_acc_rugwoolm_03',         price = 400},
            {label = 'Tapis en laine M4',            model = 'apa_mp_h_acc_rugwoolm_04',         price = 400},
            {label = 'Petit tapis en laine 1',       model = 'apa_mp_h_acc_rugwools_01',         price = 300},
            {label = 'Petit tapis en laine 3',       model = 'apa_mp_h_acc_rugwools_03',         price = 300},
            {label = 'Tapis en cuir',                model = 'hei_heist_acc_rughidel_01',        price = 500},
            {label = 'Grand tapis en laine 1',       model = 'hei_heist_acc_rugwooll_01',        price = 500},
            {label = 'Grand tapis en laine 2',       model = 'hei_heist_acc_rugwooll_02',        price = 500},
            {label = 'Grand tapis en laine 3',       model = 'hei_heist_acc_rugwooll_03',        price = 500},
        },
        ["Etageres"] = {
            {label = 'Etagère',               model = 'apa_mp_h_str_shelffloorm_02',                price = 900},
            {label = 'Étagère murale',             model = 'apa_mp_h_str_shelffreel_01',       price = 700},
            {label = 'Étagère murale moyenne',     model = 'apa_mp_h_str_shelfwallm_01',       price = 600},
            {label = 'Étagère à t-shirts 1',       model = 'prop_tshirt_shelf_1',              price = 500},
            {label = 'Étagère à t-shirts 2A',      model = 'prop_tshirt_shelf_2a',             price = 500},
            {label = 'Étagère à t-shirts 2B',      model = 'prop_tshirt_shelf_2b',             price = 500},
            {label = 'Étagère à t-shirts 2C',      model = 'prop_tshirt_shelf_2c',             price = 500},
            {label = 'Étagère d\'entrepôt 1',      model = 'prop_warehseshelf01',              price = 800},
            {label = 'Étagère d\'entrepôt 2',      model = 'prop_warehseshelf02',              price = 800},
            {label = 'Étagère d\'entrepôt 3',      model = 'prop_warehseshelf03',              price = 800},
            {label = 'Étagère maison 1',           model = 'v_ret_fh_shelf_01',                price = 600},
            {label = 'Étagère maison 2',           model = 'v_ret_fh_shelf_02',                price = 600},
            {label = 'Étagère maison 3',           model = 'v_ret_fh_shelf_03',                price = 600},
            {label = 'Étagère maison 4',           model = 'v_ret_fh_shelf_04',                price = 600},
            {label = 'Étagère à liqueur A',        model = 'v_ret_ml_liqshelfa',               price = 700},
            {label = 'Étagère à liqueur B',        model = 'v_ret_ml_liqshelfb',               price = 700},
            {label = 'Étagère à liqueur C',        model = 'v_ret_ml_liqshelfc',               price = 700},
            {label = 'Étagère à liqueur D',        model = 'v_ret_ml_liqshelfd',               price = 700},
            {label = 'Étagère à liqueur E',        model = 'v_ret_ml_liqshelfe',               price = 700},
        },
        ["Cuisines"] = {
            {label = 'Micro-ondes 2',               model = 'prop_micro_01',                   price = 450},
            {label = 'Micro-ondes 3',               model = 'prop_micro_02',                   price = 450},
            {label = 'Micro-ondes 4',               model = 'prop_micro_04',                   price = 450},
            {label = 'Réfrigérateur',              model = 'prop_fridge_01',                   price = 1500},
            {label = 'Réfrigérateur 2',              model = 'prop_fridge_03',                   price = 1500},
            {label = 'Réfrigérateur de caravane',    model = 'prop_trailr_fridge',              price = 1200},
            {label = 'Réfrigérateur à bière',        model = 'prop_bar_beerfridge_01',          price = 1000},
            {label = 'Réfrigérateur de bar 1',       model = 'prop_bar_fridge_01',              price = 1200},
            {label = 'Réfrigérateur de bar 2',       model = 'prop_bar_fridge_02',              price = 1200},
            {label = 'Réfrigérateur de bar 3',       model = 'prop_bar_fridge_03',              price = 1200},
            {label = 'Réfrigérateur de bar 4',       model = 'prop_bar_fridge_04',              price = 1200},
            {label = 'Réfrigérateur moderne A',      model = 'v_res_fridgemoda',                price = 1800},
            {label = 'Petit réfrigérateur moderne',  model = 'v_res_fridgemodsml',              price = 1300},
            {label = 'Réfrigérateur rustique',       model = 'v_res_tre_fridge',                price = 1400},
            {label = 'Réfrigérateur de magasin',     model = 'v_ret_ml_fridge',                 price = 2000},
            {label = 'Presse-agrumes',              model = 'p_kitch_juicer_s',                 price = 200},
            {label = 'Poêle à frire',              model = 'prop_kitch_pot_fry',               price = 150},
            {label = 'Grande marmite',              model = 'prop_kitch_pot_huge',              price = 300},
            {label = 'Grande casserole',            model = 'prop_kitch_pot_lrg',               price = 250},
            {label = 'Grande casserole 2',          model = 'prop_kitch_pot_lrg2',              price = 250},
            {label = 'Casserole moyenne',           model = 'prop_kitch_pot_med',               price = 200},
            {label = 'Petite casserole',            model = 'prop_kitch_pot_sm',                price = 150},
            {label = 'Cafetière',                   model = 'v_res_fa_potcof',                  price = 200},
            {label = 'Sucrier',                     model = 'v_res_fa_potsug',                  price = 100},
            {label = 'Théière',                     model = 'v_res_fa_pottea',                  price = 150},
            {label = 'Pot de cuisine 1',            model = 'v_res_m_pot1',                     price = 150},
            {label = 'Pot de salle de bain',        model = 'v_res_mbathpot',                  price = 120},
            {label = 'Pot-pourri',                  model = 'v_res_mpotpouri',                  price = 100},
            {label = 'Cafetière 2',                 model = 'v_res_r_coffpot',                  price = 200},
            {label = 'Poivrière',                   model = 'v_res_r_pepppot',                  price = 80},
            {label = 'Pot décoratif 1',             model = 'v_res_tt_pot01',                   price = 180},
            {label = 'Pot décoratif 2',             model = 'v_res_tt_pot02',                   price = 180},
            {label = 'Pot décoratif 3',             model = 'v_res_tt_pot03',                   price = 180},
            {label = 'Pot de fleurs 1',             model = 'v_ret_fh_pot01',                   price = 200},
            {label = 'Pot de fleurs 2',             model = 'v_ret_fh_pot02',                   price = 200},
            {label = 'Pot de fleurs 5',             model = 'v_ret_fh_pot05',                   price = 200},
            {label = 'Machine à laver 1',           model = 'prop_washer_01',                   price = 1200},
            {label = 'Machine à laver 2',           model = 'prop_washer_02',                   price = 1200},
            {label = 'Machine à laver 3',           model = 'prop_washer_03',                   price = 1200},
            {label = 'Panier à linge',              model = 'prop_washing_basket_01',           price = 150},
            {label = 'Machine à laver moderne',     model = 'v_ret_fh_washmach',               price = 1500},
            {label = 'Lessive en poudre 1',         model = 'v_ret_washpow1',                  price = 50},
            {label = 'Lessive en poudre 2',         model = 'v_ret_washpow2',                  price = 50},
        },
        ["Poubelles"] = {
            {label = 'Poubelle',                   model = 'prop_bin_01a',                     price = 150},
            {label = 'Poubelle 2',                  model = 'prop_bin_02a',                     price = 150},
            {label = 'Sac poubelle',                model = 'bkr_prop_fakeid_binbag_01',        price = 50},
            {label = 'Poubelle de kit',             model = 'hei_heist_kit_bin_01',            price = 150},
            {label = 'Sac poubelle 2',              model = 'hei_prop_heist_binbag',           price = 50},
            {label = 'Sac poubelle 3',              model = 'ng_proc_binbag_01a',              price = 50},
            {label = 'Sac poubelle 4',              model = 'ng_proc_binbag_02a',              price = 50},
            {label = 'Sac poubelle 5',              model = 'p_binbag_01_s',                   price = 50},
            {label = 'Poubelle 3',                  model = 'prop_bin_03a',                     price = 150},
            {label = 'Poubelle 4',                  model = 'prop_bin_04a',                     price = 150},
            {label = 'Poubelle 5',                  model = 'prop_bin_05a',                     price = 150},
            {label = 'Poubelle 6',                  model = 'prop_bin_06a',                     price = 150},
            {label = 'Poubelle 7',                  model = 'prop_bin_07a',                     price = 150},
            {label = 'Poubelle 8',                  model = 'prop_bin_07b',                     price = 150},
            {label = 'Poubelle 9',                  model = 'prop_bin_07c',                     price = 150},
            {label = 'Poubelle 10',                 model = 'prop_bin_07d',                     price = 150},
            {label = 'Poubelle 11',                 model = 'prop_bin_08a',                     price = 150},
            {label = 'Poubelle ouverte',            model = 'prop_bin_08open',                  price = 150},
            {label = 'Poubelle 12',                 model = 'prop_bin_10a',                     price = 150},
            {label = 'Poubelle 13',                 model = 'prop_bin_10b',                     price = 150},
            {label = 'Poubelle 14',                 model = 'prop_bin_11a',                     price = 150},
            {label = 'Poubelle 15',                 model = 'prop_bin_11b',                     price = 150},
            {label = 'Poubelle 16',                 model = 'prop_bin_12a',                     price = 150},
            {label = 'Poubelle CS 1',               model = 'prop_cs_bin_01',                   price = 150},
            {label = 'Poubelle CS 2',               model = 'prop_cs_bin_01_skinned',          price = 150},
            {label = 'Poubelle CS 3',               model = 'prop_cs_bin_03',                   price = 150},
            {label = 'Petite poubelle',             model = 'prop_gas_smallbin01',              price = 100},
        },
        ['Entreprise'] = {
            {label = 'Présentoir - Greasy Joe\'s',             model = 'bzzz_chalkboards_1a',              price = 100},
        },
        ['Evénement'] = {
            {label = 'Pâques - Pannier',                 model = 'bzzz_event_easter_basket_a',           price = 400},
            {label = 'Pâques - Pannier avec des oeufs',  model = 'bzzz_event_easter_basket_b',           price = 400},
            {label = 'Pâques - Lapin en chocolat',       model = 'bzzz_event_easter_bunny_a',            price = 400},
            {label = 'Pâques - Oeuf - Vert',             model = 'bzzz_event_easter_egg_a',              price = 400},
            {label = 'Pâques - Oeuf - Rose',             model = 'bzzz_event_easter_egg_b',              price = 400},
            {label = 'Pâques - Oeuf - Jaune',            model = 'bzzz_event_easter_egg_c',              price = 400},
            {label = 'Pâques - Oeuf - Bleu',             model = 'bzzz_event_easter_egg_d',              price = 400},
            {label = 'Pâques - Oeuf - Bleu foncé',       model = 'bzzz_event_easter_egg_e',              price = 400},
            -- Saint Valentine 24
            {label = 'St Valentin - Set 1 - Banc 1',       model = 'bzzz_valentine24_bench_a',              price = 1500},
            {label = 'St Valentin - Set 1 - Banc 2',       model = 'bzzz_valentine24_bench_b',              price = 1500},
            {label = 'St Valentin - Set 1 - Banc 3',       model = 'bzzz_valentine24_bench_c',              price = 1500},
            {label = 'St Valentin - Set 1 - Lumière 1',       model = 'bzzz_valentine24_light_a',              price = 500},
            {label = 'St Valentin - Set 1 - Lumière 1',       model = 'bzzz_valentine24_light_b',              price = 500},
            {label = 'St Valentin - Set 1 - Lumière 1',       model = 'bzzz_valentine24_light_c',              price = 500},
            {label = 'St Valentin - Set 1 - L Rose',       model = 'bzzz_valentine24_pink_l',              price = 500},
            {label = 'St Valentin - Set 1 - O Rose',       model = 'bzzz_valentine24_pink_o',              price = 500},
            {label = 'St Valentin - Set 1 - V Rose',       model = 'bzzz_valentine24_pink_v',              price = 500},
            {label = 'St Valentin - Set 1 - E Rose',       model = 'bzzz_valentine24_pink_e',              price = 500},
            {label = 'St Valentin - Set 1 - L Rouge',       model = 'bzzz_valentine24_red_l',              price = 500},
            {label = 'St Valentin - Set 1 - O Rouge',       model = 'bzzz_valentine24_red_o',              price = 500},
            {label = 'St Valentin - Set 1 - V Rouge',       model = 'bzzz_valentine24_red_v',              price = 500},
            {label = 'St Valentin - Set 1 - E Rouge',       model = 'bzzz_valentine24_red_e',              price = 500},
            {label = 'St Valentin - Set 1 - L Bois',       model = 'bzzz_valentine24_wood_l',              price = 500},
            {label = 'St Valentin - Set 1 - O Bois',       model = 'bzzz_valentine24_wood_o',              price = 500},
            {label = 'St Valentin - Set 1 - V Bois',       model = 'bzzz_valentine24_wood_v',              price = 500},
            {label = 'St Valentin - Set 1 - E Bois',       model = 'bzzz_valentine24_wood_e',              price = 500},
            {label = 'St Valentin - Set 1 - Rose Orange',       model = 'bzzz_valentine24_rose_orange',    price = 500},
            {label = 'St Valentin - Set 1 - Rose Rose',       model = 'bzzz_valentine24_rose_pink',        price = 500},
            {label = 'St Valentin - Set 1 - Rose Jaune',       model = 'bzzz_valentine24_rose_yellow',     price = 500},
            {label = 'St Valentin - Set 1 - Coeur rouge',       model = 'bzzz_valentine24_stone_red',     price = 500},
            {label = 'St Valentin - Set 1 - Coeur Rose',       model = 'bzzz_valentine24_stone_pink',     price = 500},
            {label = 'St Valentin - Set 1 - Coeur Bois',       model = 'bzzz_valentine24_stone_wood',     price = 500},
            -- St Valentin - Set 2
            {label = 'St Valentin - Set 2 - 01',       model = 'bzzz_love_valentines_beach_a',     price = 1500},
            {label = 'St Valentin - Set 2 - 02',       model = 'bzzz_love_valentines_beach_b',     price = 1200},
            {label = 'St Valentin - Set 2 - 03',       model = 'bzzz_love_valentines_beach_c',     price = 1500},
            {label = 'St Valentin - Set 2 - 04',       model = 'bzzz_love_valentines_beach_d',     price = 500},
            {label = 'St Valentin - Set 2 - 05',       model = 'bzzz_love_valentines_beach_e',     price = 500},
            {label = 'St Valentin - Set 2 - 06',       model = 'bzzz_love_valentines_beach_f',     price = 500},
            {label = 'St Valentin - Set 2 - 07',       model = 'bzzz_love_valentines_beach_g',     price = 500},
            {label = 'St Valentin - Set 2 - 08',       model = 'bzzz_love_valentines_beach_h',     price = 500},
        },
    }
}